language: node_js

env:
  - CXX=g++-4.8

node_js:
  - 8
  - 10
  - 12

notifications:
  email:
    - lilleman@larvit.se

before_install:
  - $CXX --version

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i

before_script:
  - mysql -e 'CREATE DATABASE test'

script: node_modules/.bin/nyc --reporter=lcov npm run test

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

addons:
  mariadb: '10.3'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
